//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcasino
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanChoiNguoi
    {
        public int MaBC { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<System.DateTime> ThoiGianVao { get; set; }
    
        public virtual BanChoi BanChoi { get; set; }
        public virtual Khachhang Khachhang { get; set; }
        public virtual TrangThai TrangThai { get; set; }
    }
}
