//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcasino
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhieuNai
    {
        public int MaKN { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> MaKhachhang { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
    }
}
