//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcasino
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLcasinoEntiy : DbContext
    {
        public QLcasinoEntiy()
            : base("name=QLcasinoEntiy")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanChoi> BanChoi { get; set; }
        public virtual DbSet<BanChoiNguoi> BanChoiNguoi { get; set; }
        public virtual DbSet<DanhThu> DanhThu { get; set; }
        public virtual DbSet<DichVu> DichVu { get; set; }
        public virtual DbSet<Hoadon> Hoadon { get; set; }
        public virtual DbSet<Khachhang> Khachhang { get; set; }
        public virtual DbSet<KhieuNai> KhieuNai { get; set; }
        public virtual DbSet<KhuVuc> KhuVuc { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMai { get; set; }
        public virtual DbSet<LichLamViec> LichLamViec { get; set; }
        public virtual DbSet<LichSuChoi> LichSuChoi { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<TaiKhoanNV> TaiKhoanNV { get; set; }
        public virtual DbSet<ThongKeDoanhThu> ThongKeDoanhThu { get; set; }
        public virtual DbSet<TrangThai> TrangThai { get; set; }
        public virtual DbSet<TroChoi> TroChoi { get; set; }
    }
}
